mini_shopping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

products/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    cat_name = models.CharField(max_length=100)
    def __str__(self):
        return self.cat_name

class Product(models.Model):
    product_name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    in_stock = models.IntegerField(default=0)

    #Color Set
    YELLOW = 'YE'
    GREEN = 'GR'
    BLACK = 'BL'
    WHITE = "WH"
    COLOR_CHOICES = (
        (YELLOW, 'Yellow'),
        (GREEN, 'Green'),
        (BLACK, 'Black'),
        (WHITE, 'White'),
    )

    color_name = models.CharField(
        max_length=50,
        choices = COLOR_CHOICES,
        default = BLACK,
    )

    #Weight set
    ONE_K = '1K'
    TWO_K = '2K'
    THREE_K = '3K'
    FOUR_K = "4K"
    WEIGHT_CHOICES = (
        (ONE_K, '1kg'),
        (TWO_K, '2kg'),
        (THREE_K, '3kg'),
        (FOUR_K, '4kg'),
    )

    weight_name = models.CharField(
        max_length=50,
        choices = WEIGHT_CHOICES,
        default = ONE_K,
    )

    description = models.TextField(null=True)
    def __str__(self):
        return self.product_name

products/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Category, Product

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'mini_shopping/index.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.order_by('-product_name')[:5]

class DetailView(generic.DetailView):
    model = Product
    template_name = 'mini_shopping/detail.html'


class CategoryView(generic.DetailView):
    model = Category
    template_name = 'mini_shopping/category.html'

products/templates/mini_shopping/category.html
<h1>{{ category.cat_name }}</h1>


<a href="{% url 'products:index' %}">Inicio</a>

products/templates/mini_shopping/detail.html
<h1>{{ product.product_name }}</h1>
<a href="{% url 'products:category' product.category.id %}"><small>{{ product.category }}</small></a>

<p><b>En stock:</b> {{ product.in_stock }}</p>

<p> {{ product.description }}</p>

<a href="{% url 'products:index' %}">Inicio</a>

products/templates/mini_shopping/index.html
{% if product_list %}
  <ul>
    {% for product in product_list %}
      <li><a href="{% url 'products:detail' product.id %}">{{ product.product_name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>Qlq perro</p>
{% endif %}